#!/bin/sh
# Xcode Cloud runs this straight after cloning, before it looks for a project.
#
# It has to exist because FixMe.xcodeproj is generated by XcodeGen and deliberately not
# committed — project.yml is the source of truth, and a checked-in project file drifts
# from it silently. Without this, Xcode Cloud clones the repo and finds nothing to build.
set -e

echo "Installing XcodeGen…"
if command -v xcodegen >/dev/null 2>&1; then
    echo "already present"
elif command -v brew >/dev/null 2>&1; then
    brew install xcodegen
else
    # Homebrew is normally on the image, but downloading the release binary keeps this
    # working if that ever stops being true.
    VERSION=2.44.1
    curl -fsSL -o /tmp/xcodegen.zip \
      "https://github.com/yonaskolb/XcodeGen/releases/download/${VERSION}/xcodegen.zip"
    unzip -oq /tmp/xcodegen.zip -d /tmp/xcodegen
    export PATH="/tmp/xcodegen/xcodegen/bin:$PATH"
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"
echo "Generating FixMe.xcodeproj from project.yml…"
xcodegen generate

# Fail here with a clear message rather than letting Xcode Cloud report "scheme not found".
if [ ! -d "FixMe.xcodeproj" ]; then
    echo "error: XcodeGen did not produce FixMe.xcodeproj" >&2
    exit 1
fi
echo "Done."
