import Foundation

/// Where the app sends someone who needs help.
///
/// App Review checks that a support route exists and works, and these must stay in step
/// with the Support URL filed in App Store Connect — see `docs/APP_STORE.md`. The hosted
/// pages are generated by `Scripts/generate-legal-html.py`.
enum SupportLinks {
    static let address = "rakshitbargotra@gmail.com"

    /// Pre-addressed mail with a subject that identifies the app and build.
    static var email: URL {
        let version = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "?"
        let build = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "?"
        var components = URLComponents()
        components.scheme = "mailto"
        components.path = address
        components.queryItems = [
            URLQueryItem(name: "subject", value: "Fix Me support (\(version) build \(build))")
        ]
        return components.url ?? URL(string: "mailto:\(address)")!
    }

    static var website: URL { FixMeSite.support }
}
